### ISSUE TITLE
Class/file naming

### ISSUE THREAD

**Issue by micros123** [projecttouch/projecttouch#9]
Hi, I've been postponing a discussion about this, because I don't want to complain before I contribute, and everyone has their own style of coding. But I keep running into this, so let's discuss it here :-)

I think the class names should be a bit more verbose. Names like 'media.js', ;list.js'  and 'library.js' could mean so many things, that it gets confusing. Especially now that there are multiple files called media.js for example. When one logs something or throws an error it is not immediately clear where it comes from. It is also not clear in the editor.

Clear naming of classes helps in production speed, as it is immediately clear what the component is for.

I'll do a few small name changes on classes I am working on and commit them, I won't start refactoring the entire project of course. We can also discuss this face to face on Monday. Hope we can agree!

**Comment by zonakusu** [comment]
The classes are placed in logic path's which include more description than a name can give. I think /js/app/views/ui/library is more than clear enough.

Also I believe we should just stick with RequireJS's naming conventions.

**Comment by micros123** [comment]
I think being more clear and more descriptive is not a bad thing. For example, what does 'ui' clarify? Aren't all views 'ui'? Or is that a convention?
Can you give me link to the RequireJS naming conventions?

**Comment by afewyards** [comment]
the ui thing is a convention. the elements that are actually placed as an ui.. the base kind of classes like panel go into the subfolder views. 

then the question about the naming conventions. a hyphen-delimited syntax is way more clearer to read and imo mixing syntaxes is a bad thing to do.

I get the point that from a source kind of perspective you would like to see camelcase, but it can't be consisted with html/css and javascript. so that's the reason why we don't do it.

**Comment by micros123** [comment]
Okay, that's fine. Totally agree we shouldn't mix syntaxes, so I'll stick to the hyphens as well.
